services:
  weaviate:
    image: semitechnologies/weaviate:1.30.7
    ports:
      - 8080:8080
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - ENABLE_MODULES=text2vec-transformers
      - DEFAULT_VECTORIZER_MODULE=text2vec-transformers
      - TRANSFORMERS_INFERENCE_API=http://t2v-transformers:8080
      - BATCH_AUTO_CREATE=true
      - BATCH_SIZE=50
      - MAX_IMPORT_GOROUTINES=4
      - REQUEST_TIMEOUT=300s
    restart: on-failure
    networks:
      - weaviate-network
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-msmarco-distilroberta-base-v2
    environment:
      ENABLE_CUDA: '0'
    networks:
      - weaviate-network
networks:
  weaviate-network:
    driver: bridge